import "@fontsource-variable/inter";
import "./globals.css";
import type { Metadata } from "next";
import { env } from "~/env";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div>Server says {env.SECRET}!</div>
        <main>{props.children}</main>
      </body>
    </html>
  );
}
